<?php
$ligas = [
    'Alka Superliga' => [
        'Brøndby IF',
        'Silkeborg IF',
        'Aarhus GF',
        'Odense Boldklub',
        'FC København',
        'Aalborg BK',
        'Viborg FF',
        'Esbjerg fB',
        'AC Horsens',
        'SønderjyskE',
        'FC Midtjylland',
        'Randers FC',
        'FC Nordsjælland',
        'Lyngby BK',
    ],
    'Pro League' => [
        'RSC Anderlecht',
        'Club Brugge',
        'Standard Liège',
        'Sp. Charleroi',
        'KRC Genk',
        'KAA Gent',
        'Sint-Truiden',
        'KVC Westerlo',
        'KV Oostende',
        'Sport. Lokeren',
        'KAS Eupen',
        'Zulte-Waregem',
        'KV Kortrijk',
        'KV Mechelen',
        'Waasland-Beveren',
        'Excel Mouscron',
    ],
    'Liga do Brasil' => [
        'Palmeiras',
        'Botafogo',
        'Fluminense',
        'Cruzeiro',
        'São Paulo',
        'Atlético Mineiro',
        'Atlético Paranaense',
        'Internacional',
        'Santos',
        'Grêmio',
        'Vitória',
        'Ponte Preta',
        'Coritiba',
        'Figueirense',
        'Sport',
        'Santa Cruz',
        'América Mineiro',
        'Chapecoense',
    ],
    'Eredivisie' => [
        'Ajax',
        'Feyenoord',
        'PSV',
        'ADO Den Haag',
        'Roda JC Kerkrade',
        'FC Utrecht',
        'AZ',
        'Willem II',
        'FC Twente',
        'Vitesse',
        'NEC',
        'SC Heerenveen',
        'PEC Zwolle',
        'FC Groningen',
        'Excelsior',
        'Go Ahead Eagles',
        'Heracles Almelo',
        'Sparta Rotterdam',
    ],
    'Premier League' => [
        'Arsenal',
        'Chelsea',
        'Everton',
        'Liverpool',
        'Manchester City',
        'Manchester United',
        'Middlesbrough',
        'Southampton',
        'Tottenham Hotspur',
        'West Ham United',
        'Leicester City',
        'Sunderland',
        'West Bromwich Albion',
        'Watford',
        'Burnley',
        'Crystal Palace',
        'Stoke City',
        'Bournemouth',
        'Hull City',
        'Swansea City',
    ],
    'EFL Championship' => [
        'Aston Villa',
        'Blackburn Rovers',
        'Leeds United',
        'Newcastle United',
        'Nottingham Forest',
        'Queens Park Rangers',
        'Birmingham City',
        'Derby County',
        'Ipswich Town',
        'Wolverhampton Wanderers',
        'Fulham',
        'Norwich City',
        'Reading',
        'Rotherham United',
        'Preston North End',
        'Sheffield Wednesday',
        'Brighton & Hove Albion',
        'Wigan Athletic',
        'Bristol City',
        'Brentford',
        'Barnsley',
        'Huddersfield Town',
        'Cardiff City',
        'Burton Albion',
    ],
    'Ligue 1'    => [
        'SC Bastia',
        'Girondins de Bordeaux',
        'En Avant Guingamp',
        'LOSC Lille',
        'Olympique Lyonnais',
        'FC Metz',
        'AS Monaco',
        'Montpellier HSC',
        'FC Nantes',
        'OGC Nice',
        'Paris Saint-Germain',
        'Stade Rennais',
        'SM Caen',
        'FC Lorient',
        'Olympique de Marseille',
        'Angers SCO',
        'Toulouse FC',
        'AS Saint-Étienne',
        'AS Nancy',
        'Dijon Football',
        'Dominos'
    ],
    'Ligue 2' => [
        'AJ Auxerre',
        'Racing Club de Lens',
        'RC Strasbourg',
        'Nîmes Olympique',
        'FC Sochaux',
        'ES Troyes AC',
        'Stade Brestois 29',
        'Stade de Reims',
        'AC Ajaccio',
        'Le Havre AC',
        'Chamois Niortais FC',
        'Stade Lavallois MFC',
        'Clermont Foot',
        'Amiens SC',
        'GFC Ajaccio',
        'Tours FC',
        'Valenciennes FC',
        'Bourg en Bresse 01',
        'Red Star FC',
        'US Orléans',
    ],
    'Bundesliga' => [
        'Bayern München',
        'Borussia Dortmund',
        'Borussia Mgladbach',
        'SC Freiburg',
        'Hamburger SV',
        '1. FC Köln',
        'Bayer 04 Leverkusen',
        'FC Schalke 04',
        'SV Werder Bremen',
        'Hertha BSC',
        '1. FSV Mainz 05',
        'VfL Wolfsburg',
        'Eintracht Frankfurt',
        'TSG 1899 Hoffenheim',
        'FC Augsburg',
        'SV Darmstadt 98',
        'FC Ingolstadt 04',
        'RB Leipzig',
    ],
    'Bundesliga 2' => [
        '1. FC Kaiserslautern',
        'TSV 1860 München',
        'VfB Stuttgart',
        'Arminia Bielefeld',
        'VfL Bochum',
        'SpVgg Greuther Fürth',
        '1. FC Nürnberg',
        'Hannover 96',
        'Dynamo Dresden',
        'Erzgebirge Aue',
        '1. FC Union Berlin',
        'Karlsruher SC',
        'SV Sandhausen',
        'Würzburger Kickers',
        'FC St. Pauli',
        'Eintracht Braunschweig',
        'Fortuna Düsseldorf',
        '1. FC Heidenheim',
    ],
    'Calcio A'    => [
        'Atalanta',
        'Inter',
        'Juventus',
        'Lazio',
        'Milan',
        'Napoli',
        'Roma',
        'Torino',
        'Udinese',
        'Bologna',
        'Chievo Verona',
        'Pescara',
        'Empoli',
        'Sampdoria',
        'Cagliari',
        'Palermo',
        'Fiorentina',
        'Genoa',
        'Crotone',
        'Sassuolo',
    ],
    'Calcio B' => [
        'Brescia',
        'Perugia',
        'Hellas Verona',
        'Ternana',
        'Ascoli',
        'Bari',
        'Avellino',
        'Salernitana',
        'Pisa',
        'Spezia',
        'Cesena',
        'Frosinone',
        'Cittadella',
        'Benevento',
        'Novara',
        'Pro Vercelli',
        'Carpi',
        'Trapani',
        'Latina',
        'Spal',
        'Vicenza',
        'Virtus Entella',
    ],
    'MLS' => [
        'Columbus Crew SC',
        'D.C. United',
        'New York Red Bulls',
        'New England Revolution',
        'Chicago Fire',
        'Colorado Rapids',
        'FC Dallas',
        'Sporting KC',
        'Los Angeles Galaxy',
        'Houston Dynamo',
        'Vancouver Whitecaps',
        'Real Salt Lake',
        'Montreal Impact',
        'Portland Timbers',
        'Seattle Sounders',
        'Toronto FC',
        'San Jose Earthquakes',
        'Philadelphia Union',
        'Orlando City SC',
        'New York City FC',
    ],
    'Tippeligaen' => [
        'Rosenborg BK',
        'Lillestrøm SK',
        'Viking FK',
        'Molde FK',
        'Tromsø IL',
        'Stabæk Fotball',
        'FK Bodø/Glimt',
        'SK Brann',
        'Vålerenga',
        'Strømsgodset Toppfotball',
        'Odds Ballklubb',
        'FK Haugesund',
        'Sogndal Fotball',
        'IK Start',
        'Aalesunds FK',
        'Sarpsborg 08 FF',
    ],
    'Scottish Prem'    => [
        'Aberdeen',
        'Celtic',
        'Heart of Midlothian',
        'Kilmarnock',
        'Motherwell',
        'Rangers',
        'Dundee FC',
        'Hamilton Academical',
        'Inverness Caledonian Thistle',
        'Ross County',
        'Partick Thistle',
        'St. Johnstone',
    ],
    'LaLiga Santander'    => [
        'Atlético de Madrid',
        'FC Barcelona',
        'RC Deportivo',
        'Real Madrid',
        'Athletic Club de Bilbao',
        'Real Betis Balompié',
        'RC Celta de Vigo',
        'RCD Espanyol',
        'Real Sociedad',
        'Real Sporting de Gijón',
        'Valencia CF',
        'Deportivo Alavés',
        'SD Eibar',
        'UD Las Palmas',
        'CA Osasuna',
        'Sevilla FC',
        'Villarreal CF',
        'Málaga CF',
        'CD Leganés',
        'Granada CF',
    ],
    'LaLiga 1|2|3'    => [
        'Real Zaragoza',
        'CD Tenerife',
        'RCD Mallorca',
        'Real Valladolid',
        'Elche CF',
        'CD Numancia',
        'Rayo Vallecano',
        'Levante UD',
        'Getafe CF',
        'UD Almería',
        'Córdoba CF',
        'Cádiz CF',
        'Nástic de Tarragona',
        'AD Alcorcón',
        'Girona FC',
        'CD Mirandés',
        'Sevilla Atlético',
        'Real Oviedo',
        'CD Lugo',
        'SD Huesca',
        'CF Reus Deportiu',
        'UCAM Murcia',
    ],
    'Allsvenskan' => [
        'IFK Göteborg',
        'Malmö FF',
        'Helsingborgs IF',
        'AIK',
        'IF Elfsborg',
        'IFK Norrköping',
        'Örebro SK',
        'Hammarby IF',
        'Djurgårdens IF',
        'BK Häcken',
        'Kalmar FF',
        'GIF Sundsvall',
        'Gefle IF',
        'Jönköpings Södra IF',
        'Falkenbergs FF',
        'Östersunds FK',
    ],
    'EFL League One' => [
        'Bolton Wanderers',
        'Charlton Athletic',
        'Millwall',
        'Shrewsbury Town',
        'Sheffield United',
        'Milton Keynes Dons',
        'Coventry City',
        'Gillingham',
        'Walsall',
        'Bradford City',
        'Oldham Athletic',
        'Chesterfield',
        'Port Vale',
        'Northampton Town',
        'Swindon Town',
        'Peterborough United',
        'Bury',
        'Scunthorpe United',
        'Oxford United',
        'Southend United',
        'Rochdale',
        'Bristol Rovers',
        'AFC Wimbledon',
        'Fleetwood Town',
    ],
    'EFL League Two' => [
        'Grimsby Town',
        'Crewe Alexandra',
        'Barnet',
        'Doncaster Rovers',
        'Exeter City',
        'Yeovil Town',
        'Morecambe',
        'Stevenage',
        'Carlisle United',
        'Portsmouth',
        'Luton Town',
        'Blackpool',
        'Plymouth Argyle',
        'Wycombe Wanderers',
        'Colchester United',
        'Cheltenham Town',
        'Notts County',
        'Mansfield Town',
        'Hartlepool United',
        'Cambridge United',
        'Leyton Orient',
        'Accrington Stanley',
        'Crawley Town',
        'Newport County',
    ],
    'SSE Airtricity League'    => [
        'Bohemian FC',
        'Shamrock Rovers',
        'Cork City',
        'St. Patricks Athletic',
        'Derry City',
        'Sligo Rovers',
        'Dundalk FC',
        'Bray Wanderers',
        'Galway United',
        'Longford Town',
        'Finn Harps',
        'Wexford Youths',
    ],
    'Ekstraklasa' => [
        'Lech Poznań',
        'Ruch Chorzów',
        'Wisła Płock',
        'Legia Warszawa',
        'Wisła Kraków',
        'Górnik Łęczna',
        'Jagiellonia Białystok',
        'Pogoń Szczecin',
        'Cracovia Kraków',
        'Zagłębie Lubin',
        'Arka Gdynia',
        'Korona Kielce',
        'Piast Gliwice',
        'Lechia Gdańsk',
        'Śląsk Wrocław',
        'Bruk-Bet Termalica Nieciecza',
    ],
    'Russian League' => [
        'CSKA Moskva',
        'Krylya Sovetov Samara',
        'Lokomotiv Moskva',
        'Anzhi Makhachkala',
        'Spartak Moskva',
        'Zenit St. Petersburg',
        'Terek Grozny',
        'Rubin Kazan',
        'FC Rostov',
        'Tom Tomsk',
        'Amkar Perm',
        'Arsenal Tula',
        'FC Ufa',
        'FC Ural',
        'FC Krasnodar',
        'FC Orenburg',
        'FK Tosno'
    ],
    'Süper Lig'    => [
        'Galatasaray',
        'Fenerbahçe',
        'Beşiktaş',
        'Trabzonspor',
        'Antalyaspor',
        'Bursaspor',
        'Medipol Başakşehir',
        'Kayserispor',
        'Gaziantepspor',
        'Gençlerbirliği',
        'Atiker Konyaspor',
        'Çaykur Rizespor',
        'Adanaspor',
        'Kasımpaşa',
        'Akhisarspor',
        'Kardemir Karabükspor',
        'Osmanlıspor',
        'Alanyaspor',
    ],
    'Rest of World'    => [
        'Olympiacos CFP',
        'PAOK FC',
        'Vasco da Gama',
        'Panathinaikos FC',
        'HJK Helsinki',
        'Shakhtar Donetsk',
        'Kaizer Chiefs',
        'Orlando Pirates',
        'Goiás',
        'Criciúma',
        'Joinville',
        'World XI',
        'Classic XI',
        'MLS All Stars',
        'Avaí',
        'adidas All-Star Team',
    ],
    'Ö Bundesliga'    => [
        'Red Bull Salzburg',
        'Sturm Graz',
        'Rapid Wien',
        'Austria Wien',
        'SV Ried',
        'SV Mattersburg',
        'SCR Altach',
        'FC Admira Wacker Mödling',
        'Wolfsberger AC',
        'SKN St. Pölten',
    ],
    'KLEAGUE Classic'    => [
        'Seongnam FC',
        'FC Seoul',
        'Suwon Samsung Bluewings',
        'Ulsan Hyundai',
        'Pohang Steelers',
        'Jeonnam Dragons',
        'Jeonbuk Hyundai Motors',
        'Jeju United',
        'Sangju Sangmu',
        'Incheon United',
        'Gwangju FC',
        'Suwon FC',
    ],
    'RSL' => [
        'FC Vaduz',
        'Grasshopper Club Zürich',
        'FC Basel',
        'FC Luzern',
        'FC St. Gallen',
        'BSC Young Boys',
        'FC Thun',
        'FC Lausanne-Sport',
        'FC Lugano',
        'FC Sion',
    ],
    'Liga NOS'    => [
        'SL Benfica',
        'FC Porto',
        'Sporting CP',
        'Chaves',
        'Vitória Setúbal',
        'Rio Ave',
        'Vitória Guimarães',
        'Belenenses',
        'Nacional',
        'Paços de Ferreira',
        'Marítimo',
        'SC Braga',
        'Boavista',
        'Moreirense',
        'Feirense',
        'Estoril Praia',
        'Arouca',
        'Tondela',
    ],
    'Camp. Scotiabank'    => [
        'Universidad de Chile',
        'Audax Italiano',
        'Universidad Católica',
        'Santiago Wanderers',
        'Unión Española',
        'Cobresal',
        'Colo-Colo',
        'CD Huachipato',
        'CD Palestino',
        'CD OHiggins',
        'Deportes Iquique',
        'Deportes Antofagasta',
        'Universidad de Concepción',
        'Everton de Viña del Mar',
        'San Luis de Quillota',
        'Deportes Temuco',
    ],
    'Liga Dimayor'    => [
        'Atlético Nacional',
        'Junior Barranquilla',
        'Deportivo Cali',
        'Independiente Medellín',
        'Independiente Santa Fe',
        'Millonarios',
        'Once Caldas',
        'Deportes Tolima',
        'Deportivo Pasto',
        'Boyacá Chicó',
        'La Equidad',
        'Envigado',
        'Patriotas Boyacá',
        'Atlético Huila',
        'Rionegro Águilas',
        'Alianza Petrolera',
        'Fortaleza CEIF',
        'Jaguares de Córdoba',
        'Cortuluá',
        'Atlético Bucaramanga',
    ],
    'LIGA Bancomer MX'    => [
        'Monarcas Morelia',
        'Monterrey',
        'Cruz Azul',
        'América',
        'Guadalajara',
        'U.N.A.M.',
        'Toluca',
        'Tigres U.A.N.L.',
        'Atlas',
        'Necaxa',
        'Santos Laguna',
        'Tiburones Rojos de Veracruz',
        'Pachuca',
        'Gallos Blancos de Querétaro',
        'Puebla',
        'León',
        'Tijuana',
        'Chiapas FC',
    ],
    'Meiji Yasuda J1'    => [
        'Júbilo Iwata',
        'Kashiwa Reysol',
        'Vissel Kobe',
        'Kashima Antlers',
        'FC Tokyo',
        'Yokohama F. Marinos',
        'Urawa Red Diamonds',
        'Kawasaki Frontale',
        'Nagoya Grampus',
        'Gamba Osaka',
        'Omiya Ardija',
        'Vegalta Sendai',
        'Albirex Niigata',
        'Sanfrecce Hiroshima',
        'Sagan Tosu',
        'Shonan Bellmare',
        'Ventforet Kofu',
        'Avispa Fukuoka',
    ],
    'Dawry Jameel'    => [
        'Al Hilal',
        'Al Ittihad',
        'Al Shabab',
        'Al Ettifaq',
        'Al Nassr',
        'Al Ahli',
        'Al Faisaly',
        'Al Fateh',
        'Al Qadisiyah',
        'Al Raed',
        'Al Taawoun',
        'Al Wehda',
        'Al Khaleej',
        'Al Batin',
    ],
    'Hyundai A-League'    => [
        'Adelaide United',
        'Brisbane Roar',
        'Central Coast Mariners',
        'Melbourne Victory',
        'Newcastle Jets',
        'Perth Glory',
        'Sydney FC',
        'Wellington Phoenix',
        'Melbourne City',
        'Western Sydney Wanderers',
    ],
    'Primera División'    => [
        'San Lorenzo de Almagro',
        'River Plate',
        'Boca Juniors',
        'Estudiantes de La Plata',
        'Gimnasia y Esgrima La Plata',
        'Racing Club de Avellaneda',
        'Vélez Sarsfield',
        'Independiente',
        'Atlético de Rafaela',
        'Arsenal de Sarandi',
        'Lanús',
        'Newells Old Boys',
        'Olimpo Bahía Blanca',
        'Banfield',
        'Colón',
        'Quilmes Atlético Club',
        'Rosario Central',
        'Patronato',
        'Belgrano de Córdoba',
        'Godoy Cruz',
        'Aldosivi',
        'Atlético Tucumán',
        'Defensa y Justicia',
        'Huracán',
        'San Martín de San Juan',
        'Club Atlético Tigre',
        'Unión Santa Fe',
        'Talleres de Córdoba',
        'Sarmiento',
        'Temperley',
        'Atlético de Rafaela',
    ]
];
$numero = 1;
$numeroRandomico = rand(1, 639);
$nomeLigaAleatorio = '';
$nomeTimeAleatorio = '';
foreach ($ligas as $nomeLiga => $times) {
    foreach ($times as $time) {
        if ($numero === $numeroRandomico) {
            $nomeLigaAleatorio = $nomeLiga;
            $nomeTimeAleatorio = $time;
        }
        $numero++;
    }
}
?>

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Duas Divs Responsivas</title>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
    <style>
        body {
            margin: 0;
            font-family: 'Montserrat', Arial, sans-serif;
            background: #f5f5f5;
        }

        .container {
            display: flex;
            flex-direction: row;
            height: 100vh;
        }

        .div-preta {
            flex: 1;
            background: #000;
            color: #fff;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 2rem;
        }

        .div-amarela {
            flex: 1;
            background: #FFD600;
            color: #222;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 2rem;
        }

        @media (max-width: 700px) {
            .container {
                flex-direction: column;
            }

            .div-preta,
            .div-amarela {
                font-size: 1.2rem;
                height: 50vh;
            }
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="div-preta">Liga: <?php echo $nomeLigaAleatorio ?></div>
        <div class="div-amarela">Time: <?php echo $nomeTimeAleatorio ?></div>
    </div>
</body>

</html>